server:
    port: 8080

spring:
  h2:
    console:
      enabled: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:saga-not
    username: sa

